### ISSUE TITLE
Array<T> type

### ISSUE THREAD

**Issue by AzP** [GPUOpen-Tools/amd_tootle#11]
I'm trying to build Tootle an Windows 10 and I'm unable to get it to build.

What is the Array<T> type, and where is it defined? I installed the DirectX SDK (which seemed to collide with other versions of the DirectX runtime already installed) but I still get the error.

Do you usually build the tool with the define of _SOFTWARE_ONLY_VERSION or is it not enabled by default?

**Comment by bpurnomo** [comment]
Thanks for this bug report.  I have confirmed the issue.
Apparently, the recent code merges have broken the D3D path (and 32-bit builds).  We will work on a fix.  In the meanwhile, perhaps you can use the sources from the initial commit (https://github.com/GPUOpen-Tools/amd-tootle/commit/4452c5bb4c472789a66e06586bea5800685529c4)

**Comment by AzP** [comment]
Thank you!

**Comment by bpurnomo** [comment]
This issue should be fixed in https://github.com/GPUOpen-Tools/amd-tootle/commit/cdde8da05a52bd80488dfd498cef2cac4bbbf332.
Please close the issue once you have confirmed the fix.

**Comment by AzP** [comment]
It builds now, thank you!
