### ISSUE TITLE
List of permutation to remap old indexes into new

### ISSUE THREAD

**Issue by giordi91** [GPUOpen-Tools/amd_tootle#12]
Hi, first of all amazing library, super easy to compile and process obj! Well done!
The only thing that right now is preventing me in using it is the ability to know what vertices got moved and how.
It works perfectly for static objects that don't need any kind of processing, but for animated objects the problem appears, for example skincluster ,when I export from the modelling software (autodesk maya) I store skinning information based on the current vertex order, before it was exported. With the reordering of the vertices my data is no longer valid since what was vertex 1 now has become vertex 10 and so on, this mean that mesh vertices and bone indices no longer match.
Right now the only way I see it is brute forcing vertex matching afterwards but is going to be as slow process. Would it be possible to get a list of permutations out of the tool? In this way I would be able to quickly remap the needed data to the needed indexes.
I am also open to other suggestions in how to achieve the wanted mapping.

M.

**Comment by bpurnomo** [comment]
Hi,
   Thank you for the feedback.  We are glad that you find this library useful.

Are you looking for the vertex mapping that is stored in pnVertexRemapping (see https://github.com/GPUOpen-Tools/amd-tootle/blob/master/src/TootleSample/Tootle.cpp#L1185) used by the "TootleSample -p" option?

**Comment by giordi91** [comment]
Is the pnVertexRemapping a flat buffer of indeces? something like of the form:
old new old new old new old new .....
Where old is the old index for the vertex and new the new one.
The way i worked around that is the following:
Since I was in maya I was using python, but i would have don't it in c++ aswell. What I did i grabbed the first obj class I found on the net: http://www.pygame.org/wiki/OBJFileLoader

Then I read back in both objs, the old and the tootle version.
And did a brute force scan to match vertices up to a tollerance and dumped a list of lists:
example : [[0,1],[2,40] ....]
I can provide you a sample exported data if needed, but here is the overall code I quickly put together
[obj_exporter.zip](https://github.com/GPUOpen-Tools/amd-tootle/files/274573/obj_exporter.zip)

you can check the obj_remapping function is really simple. 
That data get then saved to a json file and read back in in the skincluster export process where I use that data to remap the skin data structure to reflect the obj.

Since looks like the needed data is already present in the tootle code, would it be possible to add an option taking a path to where to dump the mapping? Data format is no really a big deal as long as can be parsed easily.

What are your thoughts on the matter?
:

**Comment by bpurnomo** [comment]
Please try out the latest code in the master branch.  
Tootle will now output the vertex remapping indices as part of the output obj.  The vertex remapping indices are output as comments (each line is prefixed with "#vertexRemap = " with a maximum of 50 indices per line).  Note that the vertex index is 0-based.
As an example the following output line
#vertexRemap = 3 7 0 10
means that
v3 from the input obj becomes v0 in the output obj
v7 from the input obj becomes v1 in the output obj
v0 from the input obj becomes v2 in the output obj
v10 from the input obj becomes v3 in the output obj

Let me know if this works for you.

**Comment by giordi91** [comment]
Thanks a lot for the work! personally I would rather get an external filer, can have the same name of the output file and maybe extension tootle? can just be a comma separated value file, but would be more convenient for me due to the fact I am using an external library to parse the OBJ, I am not performing it myself, and as mentioned I need the extra data to perform data formatting for example skinning data.
Having an external file will facilitate the reading of the file without need to modify the obj parser. 
Either way I can handle that now, my is just a personal preference.
What are your thoughts..

**Comment by bpurnomo** [comment]
You can treat the output obj file as the extra external file.  You can read this file without an obj parser since an obj file is a text file.  Just ignore any lines that don't start with "#vertexRemap = ".
Would that work for you?

**Comment by giordi91** [comment]
yeah that will do thanks

M.
