### ISSUE TITLE
Runtime optimization headroom?

### ISSUE THREAD

**Issue by AndrewJDR** [GPUOpen-Tools/amd_tootle#15]
This is not a bug, but a general question for AMD engineer(s) on this project:
Firstly, do you have any general tips on getting the lowest runtimes possible with tootle? For context, I'm currently only calling TootleOptimizeVCache().

Beyond that, do you suppose there's much headroom for run time reductions with simd and multithreading? Particularly within the Vertex prefetch cache optimization and Vertex cache optimization phases? Is there any low hanging fruit, or will run time optimization be pretty tough work at this point?

**Comment by bpurnomo** [comment]
You can get zero runtime overhead by performing the tootle optimization as a pre-process step and bake out the resulting optimized mesh.  This approach will work with static meshes.  For non-static meshes case, perhaps running your runtime under a profiler may help to pin point potential area for improvements.  It is likely there a lot of headroom to reduce the running time (if this is deemed to be your bottleneck), if you can cluster and parallelize the triangle sorting algorithm.

**Comment by AndrewJDR** [comment]
Great, I'll have a look at that. Thanks!
