### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Tools/amd_tootle#5]
I would like to point out that identifiers like "[`_BBOX_`](https://github.com/GPUOpen-Tools/amd-tootle/blob/677497a4e459fbc3654cd5fe19085a708befe49f/src/TootleLib/bbox.h#L6)" and "[`_JML_SCALAR_H_`](https://github.com/GPUOpen-Tools/amd-tootle/blob/677497a4e459fbc3654cd5fe19085a708befe49f/src/TootleLib/RayTracer/Math/JMLScalar.h#L6)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by bpurnomo** [comment]
Please feel free to create a pull request for such issue.

**Comment by elfring** [comment]
Does [such an issue](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797) need any more considerations on the general software development infrastructure (by AMD) in the background since I reported similar issues for related software components recently?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?
