### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Tools/amd_tootle#6]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/GPUOpen-Tools/amd-tootle/blob/4452c5bb4c472789a66e06586bea5800685529c4/src/TootleSample/Tootle.cpp#L806)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by bpurnomo** [comment]
Please feel free to create a pull request

**Comment by bpurnomo** [comment]
This is no longer an issue with #8

**Comment by elfring** [comment]
I find my general software design concern still valid. Do any possibilities remain in [the implementation of the function "main"](https://github.com/GPUOpen-Tools/amd-tootle/blob/966388b02ac869e0240b6a410c797d77579e3407/src/TootleSample/Tootle.cpp#L777) for the occurrence of C++ exceptions?
