### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Tools/amd_tootle#7]
Would you like to add more error handling for return values from functions like the following?
- [fgets](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fgets.html) ⇒ [ObjLoader::LoadGeometry](https://github.com/GPUOpen-Tools/amd-tootle/blob/5ccb506d6400ed8c9ff5203cfe79accb60c9df46/src/TootleSample/ObjLoader.cpp#L45)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [PrintAlgorithm](https://github.com/GPUOpen-Tools/amd-tootle/blob/4452c5bb4c472789a66e06586bea5800685529c4/src/TootleSample/Tootle.cpp#L670)

**Comment by bpurnomo** [comment]
Please feel free to create a pull request

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B) also for this software?
